default:
  image: openjdk:11-jdk

build-job:
  stage: build
  script: 
    - ./gradlew assemble

test-job:
  stage: test
  script: 
    - echo "Testing..."

deploy-job:
  stage: deploy
  script:
    - java -jar /app.jar
