default:
  image: openjdk:11-jdk

test-job:
  stage: test
  script:
    - ./gradlew test

build-job:
  stage: build
  script: 
    - ./gradlew assemble
  artifacts:
    when: always
    paths:
      - build/libs/*.jar
